# Site settings
title: CI and CD with GitHub
description: A demo blog
email: aleksandr.chirko@gmail.com
github_username:  achirko
baseurl:
url: https://achirko-ci-cd-workshop.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

# Build settings
markdown: kramdown
